#!/usr/bin/env bash

# This script will mount a source tarball into a thin Arc Linux container and
# invoke`makepkg` so as to make an Arch package.  It's meant for use during
# mpdpopm development, as a check that my latest changes won't break anything
# at release-time when it's time to package the latest mpdpopm.

# It is presumably run from the root mpdpopm directory.

# Invoke as `admin/build-dev-arch-pkg mpdpopm-${version}.tar.gz`

set -ex
docker build -t mpdpopm-arch:latest -f admin/Dockerfile-arch --label "mpdpopm-arch" .

here=$(pwd)
script=${here}/admin/build-dev-arch-pkg-cnt
pkgbuild=${here}/admin/PKGBUILD
tarball=${here}/$1

docker_args="-it"
docker_args="$docker_args -v ${script}:/build-dev-pkg:ro"
docker_args="$docker_args -v ${tarball}:/$1:ro"
docker_args="$docker_args -v ${pkgbuild}:/PKGBUILD"
docker_args="$docker_args --privileged"
docker_args="$docker_args --ulimit core=-1"
docker_args="$docker_args -u mgh"
docker_args="$docker_args --name=mpdpopm-dev-arch"

docker container rm -f mpdpopm-dev-arch

# Un-comment to just drop into the container & experiment
# cmd="docker run ${docker_args} mpdpopm-arch:latest"
cmd="docker run ${docker_args} mpdpopm-arch:latest /build-dev-pkg $1"
exec $cmd
