#!/bin/bash

set -ex
source $HOME/.cargo/env
base="$(basename $1 .tar.gz)"
version="${base:8}"
cp -v /"$1" /tmp
cd /tmp
tar -xf "$1"
cd mpdpopm-${version}
cp -v /LICENSE .
./configure
cd mpdpopm
cargo deb
ls -Alh target/debian
sudo dpkg --debug=2 -i target/debian/mpdpopm_${version}-1_amd64.deb
mppopm --version
mppopm --help
test -f /usr/local/share/info/mpdpopm.info
sudo dpkg --debug=2 -r mpdpopm
sudo cp -v target/debian/mpdpopm_${version}-1_amd64.deb /mpdpopm

