#!/bin/bash

set -ex
base="$(basename $1 .tar.gz)"
version="${base:8}"
cp -v /$1 /tmp
cp -v /PKGBUILD /tmp
cd /tmp
makepkg -g >> PKGBUILD
makepkg --log
sudo pacman --noconfirm -Uv mpdpopm-${version}-1-x86_64.pkg.tar.zst
mppopm --version
mppopm --help
test -f /usr/local/share/info/mpdpopm.info.gz
sudo pacman --noconfirm -R mpdpopm
cp -v mpdpopm-${version}-1-x86_64.pkg.tar.zst /mpdpopm
