# Docker image for building, debugging & packaging    -*- mode: dockerfile; -*-
FROM archlinux:latest AS base

# Bootstrap
RUN pacman --noconfirm -Syu && \
	cp -v /etc/pacman.conf /etc/pacman.conf.orig && \
	sed -e 's/^NoExtract/# NoExtract/' /etc/pacman.conf > /tmp/pacman.conf.tmp && \
	cp -v /tmp/pacman.conf.tmp /etc/pacman.conf

# WORKAROUND for glibc 2.33 and old Docker
# See https://github.com/actions/virtual-environments/issues/2658
# Thanks to https://github.com/lxqt/lxqt-panel/pull/1562
RUN patched_glibc=glibc-linux4-2.33-4-x86_64.pkg.tar.zst && \
    curl -LO "https://repo.archlinuxcn.org/x86_64/$patched_glibc" && \
    bsdtar -C / -xvf "$patched_glibc"

RUN pacman --noconfirm -S man-db man-pages vim base-devel gdb rust cargo && \
 	ln -sf /usr/share/zoneinfo/America/Los_Angeles /etc/localtime && \
	useradd -ms /bin/bash -G users,wheel mgh && \
	echo 'mgh:mgh' | chpasswd && \
	echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
	mkdir /cores && chmod 777 /cores && \
	echo "kernel.core_pattern=/cores/core.%e.%p" >> /etc/sysctl.d/50-coredump.conf

# TODO(sp1ff): needed?
# sysctl -p /etc/sysctl.d/50-coredump.conf
# RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y

USER mgh

ENV PATH="/home/mgh/.cargo/bin:${PATH}"

RUN cargo install cargo-aur && \
	cargo install cargo-arch

